import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Swiper, SwiperSlide } from 'swiper/react'
import  SwiperCore, {Navigation, Pagination, EffectCube, Autoplay} from 'swiper'
import './../node_modules/swiper/swiper-bundle.css'

SwiperCore.use([Navigation, Pagination, EffectCube, Autoplay])

export default function Home() {

  const slides = []

  for(let i = 0; i < 5; i += 1){
    slides.push(
      <SwiperSlide key={`slide-${i}`} tag="li">
        <img src={`https://picsum.photos/id/${i + 1}/500/300`}/>
      </SwiperSlide>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Swiper 

        effect={'cube'} grabCursor={true} cubeEffect={{
          "shadow": true,
          "slideShadows": true,
          "shadowOffset": 20,
          "shadowScale": 0.94
        }} pagination={true} className="mySwiper"

        autoplay={{
          "delay": 2500,
          "disableOnInteraction": false
        }}
          id="main" 
          tag="section" 
          wrapperTag="ul" 
          navigation 
          pagination={{
            type: "progressbar"
          }
          }
          spaceBetween={0}
          slidesPerView={1}
          onInit={(swiper) => console.log('Swiper INICIADO')}
          onSlideChange={(swiper) => console.log('Swiper changed to:'+swiper.activeIndex)}
          onReachEnd={(swiper) => console.log("Swiper FINALIZADO")}
          >
          {slides}
        </Swiper>
      </main>

     
    </div>
  )
}
